// CommonJS preload to ensure Electron can load without ESM import errors
// Mirrors the API exposed by src/preload.ts
// (Loaded via BrowserWindow.webPreferences.preload)

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('foundry', {
  run: (args) => ipcRenderer.invoke('foundry:run', args),
  buildWithProgress: (count) => ipcRenderer.invoke('foundry:buildWithProgress', count),
  pauseBuild: () => ipcRenderer.invoke('foundry:pauseBuild'),
  resumeBuild: () => ipcRenderer.invoke('foundry:resumeBuild'),
  stopBuild: () => ipcRenderer.invoke('foundry:stopBuild'),
  onBuildProgress: (handler) => { ipcRenderer.on('build-progress', (_evt, data) => handler(data)); },
  previewWithProgress: (count) => ipcRenderer.invoke('foundry:previewWithProgress', count),
  pausePreview: () => ipcRenderer.invoke('foundry:pausePreview'),
  resumePreview: () => ipcRenderer.invoke('foundry:resumePreview'),
  stopPreview: () => ipcRenderer.invoke('foundry:stopPreview'),
  onPreviewProgress: (handler) => { ipcRenderer.on('preview-progress', (_evt, data) => handler(data)); },
  chooseProjectDir: () => ipcRenderer.invoke('foundry:chooseProjectDir'),
  importProjectFolder: () => ipcRenderer.invoke('foundry:importProjectFolder'),
  getProjectDir: () => ipcRenderer.invoke('foundry:getProjectDir'),
  setProjectDir: (dir) => ipcRenderer.invoke('foundry:setProjectDir', dir),
  readConfig: () => ipcRenderer.invoke('foundry:readConfig'),
  readConfigAt: (dir) => ipcRenderer.invoke('foundry:readConfigAt', dir),
  writeConfig: (json) => ipcRenderer.invoke('foundry:writeConfig', json),
  previewEffects: (config) => ipcRenderer.invoke('foundry:previewEffects', config),
  previewLive: (config, count, seed) => ipcRenderer.invoke('foundry:previewLive', config, count, seed),
  chooseDirInsideProject: () => ipcRenderer.invoke('foundry:chooseDirInsideProject'),
  readFile: (relativePath) => ipcRenderer.invoke('foundry:readFile', relativePath),
  readFileBase64: (relativePath) => ipcRenderer.invoke('foundry:readFileBase64', relativePath),
  ensureDirs: (relativePaths) => ipcRenderer.invoke('foundry:ensureDirs', relativePaths),
  listImages: (relativePath) => ipcRenderer.invoke('foundry:listImages', relativePath),
  openInExplorer: (relativePath) => ipcRenderer.invoke('foundry:openInExplorer', relativePath),
  listDir: (relativePath) => ipcRenderer.invoke('foundry:listDir', relativePath),
  deletePath: (relativePath) => ipcRenderer.invoke('foundry:deletePath', relativePath),
  renameFiles: (pairs) => ipcRenderer.invoke('foundry:renameFiles', pairs),
  openExternal: (url) => ipcRenderer.invoke('foundry:openExternal', url),
  saveBase64: (b64, relPath) => ipcRenderer.invoke('foundry:fsSave', b64, relPath),
  listFiles: (relDir) => ipcRenderer.invoke('foundry:fsList', relDir),
  deleteFile: (relPath) => ipcRenderer.invoke('foundry:fsDelete', relPath),
  saveJson: (relPath, json) => ipcRenderer.invoke('foundry:saveJson', relPath, json),
  exportSite: (payload) => ipcRenderer.invoke('foundry:exportSite', payload),
  deploySite: (payload) => ipcRenderer.invoke('foundry:deploySite', payload),
  previewSite: () => ipcRenderer.invoke('foundry:previewSite'),
  pickImage: () => ipcRenderer.invoke('foundry:pickImage'),
  auditAssets: (opts) => ipcRenderer.invoke('foundry:auditAssets', opts || {}),
  auditOutputs: (opts) => ipcRenderer.invoke('foundry:auditOutputs', opts || {}),
  packsList: () => ipcRenderer.invoke('foundry:packsList'),
  packsRead: (id) => ipcRenderer.invoke('foundry:packsRead', id),
  packsImport: (opts) => ipcRenderer.invoke('foundry:packsImport', opts || {}),
  packsDelete: (id) => ipcRenderer.invoke('foundry:packsDelete', id),
  launchStatus: () => ipcRenderer.invoke('foundry:launchStatus'),
  launchEstimate: () => ipcRenderer.invoke('foundry:launchEstimate'),
  launchDeploy: (opts) => ipcRenderer.invoke('foundry:launchDeploy', opts || {}),
  launchSetCaps: (opts) => ipcRenderer.invoke('foundry:launchSetCaps', opts),
  launchSetPrices: (opts) => ipcRenderer.invoke('foundry:launchSetPrices', opts),
  launchSetPhase: (opts) => ipcRenderer.invoke('foundry:launchSetPhase', opts),
  launchReveal: (opts) => ipcRenderer.invoke('foundry:launchReveal', opts),
  launchFreeze: (opts) => ipcRenderer.invoke('foundry:launchFreeze', opts || {}),
  launchWithdraw: (opts) => ipcRenderer.invoke('foundry:launchWithdraw', opts || {}),
  launchSetAllowlist: (opts) => ipcRenderer.invoke('foundry:launchSetAllowlist', opts),
  launchConsole: () => ipcRenderer.invoke('foundry:launchConsole'),
  solanaLaunchStatus: () => ipcRenderer.invoke('foundry:solanaLaunchStatus'),
  solanaCreate: (opts) => ipcRenderer.invoke('foundry:solanaCreate', opts || {}),
  solanaInsertItems: (opts) => ipcRenderer.invoke('foundry:solanaInsertItems', opts || {}),
});
